# Task 3 — Manual (Human) Evaluation

Load the `assignment_01.xlsx` produced in Task 2, add a cost column, manually rate 10–15 products, compute final scores, and analyze which criteria performed best and worst.

In [32]:
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from dotenv import load_dotenv

sys.path.insert(0, str(Path.cwd().parent))
load_dotenv(Path.cwd().parent / ".env")

from shared.config import GENERATION_MODEL, OUTPUT_EXCEL
from shared.constants import CRITERIA, final_score
from shared.utils import calculate_cost, rate_cost, rate_latency, rate_length

In [33]:
df = pd.read_excel(OUTPUT_EXCEL)
print(f"{len(df)} products loaded")
df.head(3)

50 products loaded

,product_name,Product_attribute_list,material,warranty,generated_description,latency_ms,input_tokens,output_tokens,Fluency,Grammar,Tone,Length,Grounding,Latency,Cost,final_score,cost_usd
0,Apple iPhone 15 Pro,"features: A17 Pro chip, 120 Hz ProMotion displ...","titanium frame, Ceramic Shield glass",1‑year limited warranty,Experience the power and performance of the Ap...,1454.7,303,98,good,good,good,good,good,good,good,pass,0.000080
1,Samsung Galaxy S24 Ultra,"features: 200 MP camera, S‑Pen support, 120 Hz...","Armor Aluminum frame, Gorilla Glass Victus",1‑year limited warranty,Capture every detail with the stunning 200MP c...,1058.3,303,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000082
2,Google Pixel 8 Pro,"features: Tensor G3 chip, Magic Eraser, 50 MP ...","matte glass back, aluminum frame",1‑year limited warranty,Capture stunning moments with the Google Pixel...,937.5,300,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000079

## 1. Cost Calculation

Convert `input_tokens` and `output_tokens` to USD using the per-1K-token pricing for Gemma-2-9b-it. Note: input and output tokens can be priced differently.

In [34]:
df["cost_usd"] = df.apply(
    lambda row: calculate_cost(GENERATION_MODEL, row["input_tokens"], row["output_tokens"]),
    axis=1,
)

print(f"Total cost: ${df['cost_usd'].sum():.6f}")
print(f"Avg cost per call: ${df['cost_usd'].mean():.6f}")
df[["product_name", "input_tokens", "output_tokens", "cost_usd"]].head()

Total cost: $0.003980
Avg cost per call: $0.000080

                      product_name  input_tokens  output_tokens  cost_usd
0              Apple iPhone 15 Pro           303             98  0.000080
1         Samsung Galaxy S24 Ultra           303            109  0.000082
2               Google Pixel 8 Pro           300             96  0.000079
3       Sony WH‑1000XM5 Headphones           300             95  0.000079
4  Bose QuietComfort Ultra Earbuds           289             99  0.000078

## 2. Rate Each Criterion (10–15 products)

15 products are selected (evenly spaced across the dataset) for manual rating of each criterion as good / ok / bad according to the rubric from Task 1.

Latency and Cost are rated programmatically based on the thresholds in the rubric.

In [35]:
# Select 15 evenly spaced indices for manual evaluation
import numpy as np

EVAL_COUNT = 15
eval_indices = np.linspace(0, len(df) - 1, EVAL_COUNT, dtype=int).tolist()
print(f"Products selected for evaluation (indices): {eval_indices}")
print()
for i in eval_indices:
    row = df.iloc[i]
    word_count = len(row["generated_description"].split())
    print(f"--- [{i}] {row['product_name']} ({word_count} words) ---")
    print(row["generated_description"])
    print()

Products selected for evaluation (indices): [0, 3, 7, 10, 14, 17, 21, 24, 28, 31, 35, 38, 42, 45, 49]

--- [0] Apple iPhone 15 Pro (66 words) ---
Experience the power and performance of the Apple iPhone 15 Pro.  Fueled by the groundbreaking A17 Pro chip, this compact powerhouse delivers a seamless user experience with its 120Hz ProMotion display.  The durable titanium frame and Ceramic Shield glass ensure lasting protection, while USB‑C fast charging keeps you connected. Backed by a 1-year limited warranty, the iPhone 15 Pro is ready to elevate your mobile experience.

--- [3] Sony WH‑1000XM5 Headphones (62 words) ---
Escape into your music with the Sony WH-1000XM5 Headphones. Enjoy immersive sound and crystal-clear calls thanks to advanced active noise cancelling technology.  With a comfortable, large design and plush synthetic leather earcups, you can wear these headphones for hours on end.  The impressive 30-hour battery life and Bluetooth 5.2 connectivity ensure uninterrupted listening, while a 1-year limited warranty provides peace of mind.

--- [7] Apple MacBook Air 13″ (M3) (65 words) ---
Experience the power and portability of the new MacBook Air 13” with the groundbreaking M3 chip.  Enjoy an incredible 18 hours of battery life, perfect for work or play, and stay connected with the high-definition 1080p camera.  Crafted from a durable recycled aluminum unibody, this MacBook Air is both stylish and sustainable. Backed by a 1-year limited warranty, you can be confident in your purchase.

--- [10] Fitbit Charge 6 (76 words) ---
Stay on top of your fitness goals with the Fitbit Charge 6.  This stylish fitness tracker features a built-in GPS and heart-rate monitor to keep you informed about your progress.  Enjoy up to 7 days of battery life on a single charge, so you can wear it all week long.  The Fitbit Charge 6 is available in multiple colors to match your personal style and comes with a 1-year limited warranty for your peace of mind.

--- [14] PlayStation 5 Slim (76 words) ---
Experience the future of gaming with the PlayStation 5 Slim. Immerse yourself in stunning visuals with ray tracing technology and feel every detail with the haptic feedback controller. This sleek console boasts a spacious 1TB SSD for lightning-fast loading times, ensuring uninterrupted gameplay. Enjoy extended gaming sessions thanks to the long-lasting battery.  Crafted with a durable plastic shell and backed by a 1-year limited warranty, the PlayStation 5 Slim is ready to elevate your gaming experience.

--- [17] Keurig K‑Supreme Plus Smart (60 words) ---
Brew your perfect cup every time with the Keurig K-Supreme Plus Smart.  This brewer features innovative multistream extraction technology and BrewID to optimize each cup. Its large 78-oz reservoir keeps you going throughout the day, while the sleek brushed stainless steel accents add a touch of modern style to your kitchen. Enjoy peace of mind with the 1-year limited warranty.

--- [21] Yeti Rambler 20 oz Tumbler (64 words) ---
Keep your drinks perfectly chilled or piping hot all day long with the Yeti Rambler 20 oz Tumbler. Crafted from durable, kitchen-grade stainless steel, this compact tumbler is double-wall vacuum insulated to prevent temperature fluctuations.  The secure MagSlider lid keeps spills at bay, making it perfect for on-the-go adventures. Yeti backs this tumbler with a 5-year warranty, proving its commitment to quality and durability.

--- [24] Contigo Autoseal West Loop 16 oz (66 words) ---
Stay hydrated in style with the Contigo Autoseal West Loop! This compact tumbler features a convenient autoseal lid that keeps your drinks spill-proof, so you can toss it in your bag without worry. Double-wall insulation keeps your beverages hot or cold for hours, while the durable stainless steel construction ensures it's built to last.  Plus, it's backed by a lifetime warranty for ultimate peace of mind.

--- [28] Patagonia Black Hole 32 L Backpack (76 words) ---
The Patagonia Black Hole 32L Backpack is built for adventure, big and small. Crafted from durable 100% recycled polyester ripstop, this weather-resistant pack is ready for anything.  A spacious interior handles all your gear, while a dedicated laptop sleeve keeps your electronics safe.  Padded straps ensure comfortable carrying, whether you're navigating city streets or trekking through the wilderness. Backed by Patagonia's legendary lifetime warranty, the Black Hole 32L is a reliable companion for years to come.

--- [31] LEGO Icons Botanical Orchid 10311 (71 words) ---
Bring the beauty of nature indoors with the LEGO Icons Botanical Orchid 10311. This stunning set features 608 pieces crafted from high-quality ABS plastic bricks, allowing you to build a lifelike orchid with adjustable blooms.  Display this decorative masterpiece in your home and enjoy the satisfaction of a rewarding build.  Plus, with our lifetime brick replacement guarantee, you can be confident that your orchid will stay beautiful for years to come.

--- [35] Sonos Move 2 (78 words) ---
The Sonos Move 2 is the ultimate portable speaker, bringing your favorite music anywhere with ease. Featuring both WiFi and Bluetooth connectivity, you can enjoy seamless streaming at home or on the go.  With a long-lasting 24-hour battery and automatic Trueplay tuning, your music will always sound its best. Plus, the durable shock-resistant shell ensures your Move 2 can handle any adventure. Backed by a 1-year limited warranty, the Move 2 is ready to elevate your listening experience.

--- [38] Eufy Video Doorbell Dual (71 words) ---
See and secure your home with the Eufy Video Doorbell Dual.  This intelligent doorbell features two cameras, capturing both a wide view of your doorstep and a zoomed-in shot for package detection. With 2K resolution, you'll see every detail in stunning clarity.  The long-lasting battery means you can enjoy reliable protection without worrying about frequent charging.  Plus, your purchase is backed by a 1-year limited warranty for added peace of mind.

--- [42] Razer DeathAdder V3 Pro (72 words) ---
Experience unparalleled speed and precision with the Razer DeathAdder V3 Pro. This ultralight gaming mouse, weighing in at just 63 grams, is engineered for lightning-fast movements.  The cutting-edge 30K DPI Focus Pro sensor ensures pinpoint accuracy, while the long-lasting battery keeps you in the game.  Crafted from durable plastic, the DeathAdder V3 Pro is built to withstand intense gaming sessions. Backed by a 2-year warranty, you can be confident in your investment.

--- [45] SanDisk Extreme PRO 128 GB SDXC (64 words) ---
Capture every moment in brilliant detail with the SanDisk Extreme PRO 128GB SDXC memory card.  This card features UHS-I U3 technology and blazing-fast 200MB/s read speeds, ensuring smooth performance for your high-resolution photos and videos. Built tough with waterproof construction, the Extreme PRO is ready for any adventure. Backed by a lifetime limited warranty, you can trust SanDisk to deliver exceptional quality and reliability.

--- [49] ASUS ProArt PA278QV Monitor (66 words) ---
The ASUS ProArt PA278QV is a stunning 27" monitor, perfect for professionals who demand color accuracy.  With a crisp 2560x1440 IPS display, 100% sRGB coverage, and Calman Verified calibration, your visuals will be vibrant and true to life. The lightweight design and sturdy metal stand make it easy to set up and adjust for optimal viewing. Plus, enjoy peace of mind with the included 3-year warranty.

In [36]:
# Keys: product index -> {criterion: rating}
# Only Fluency, Grammar, Tone, Grounding need manual judgment.
# Length, Latency, Cost are computed automatically.

manual_ratings: dict[int, dict[str, str]] = {
    0:  {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    3:  {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    7:  {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "ok"},
    10: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    14: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    17: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    21: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    24: {"Fluency": "good", "Grammar": "good", "Tone": "ok",   "Grounding": "good"},
    28: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    31: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    35: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    38: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    42: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "ok"},
    45: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
    49: {"Fluency": "good", "Grammar": "good", "Tone": "good", "Grounding": "good"},
}

assert len(manual_ratings) >= 10, (
    f"Rate at least 10 products. Currently rated: {len(manual_ratings)}"
)

## 3. Apply Final Score

In [37]:
for idx, human_scores in manual_ratings.items():
    row = df.iloc[idx]
    full_ratings = {
        **human_scores,
        "Length": rate_length(row["generated_description"]),
        "Latency": rate_latency(row["latency_ms"]),
        "Cost": rate_cost(row["cost_usd"]),
    }
    for criterion, rating in full_ratings.items():
        df.at[idx, criterion] = rating
    df.at[idx, "final_score"] = final_score(full_ratings)

evaluated = df[df["final_score"].isin(["pass", "fail"])]
print(f"Evaluated {len(evaluated)} products")
evaluated[["product_name"] + CRITERIA + ["final_score"]]

Evaluated 15 products

,product_name,Fluency,Grammar,Tone,Length,Grounding,Latency,Cost,final_score
0,Apple iPhone 15 Pro,good,good,good,good,good,good,good,pass
3,Sony WH‑1000XM5 Headphones,good,good,good,good,good,good,good,pass
7,Apple MacBook Air 13″ (M3),good,good,good,good,ok,good,good,pass
10,Fitbit Charge 6,good,good,good,good,good,good,good,pass
14,PlayStation 5 Slim,good,good,good,good,good,good,good,pass
17,Keurig K‑Supreme Plus Smart,good,good,good,good,good,good,good,pass
21,Yeti Rambler 20 oz Tumbler,good,good,good,good,good,good,good,pass
24,Contigo Autoseal West Loop 16 oz,good,good,ok,good,good,good,good,pass
28,Patagonia Black Hole 32 L Backpack,good,good,good,good,good,good,good,pass
31,LEGO Icons Botanical Orchid 10311,good,good,good,good,good,good,good,pass
35,Sonos Move 2,good,good,good,good,good,good,good,pass
38,Eufy Video Doorbell Dual,good,good,good,good,good,good,good,pass
42,Razer DeathAdder V3 Pro,good,good,good,good,ok,good,good,pass
45,SanDisk Extreme PRO 128 GB SDXC,good,good,good,good,good,good,good,pass
49,ASUS ProArt PA278QV Monitor,good,good,good,good,good,good,good,pass

In [38]:
df.to_excel(OUTPUT_EXCEL, index=False)
print(f"Saved to {OUTPUT_EXCEL}")

Saved to /Users/nisim/Desktop/Nebuis Academy/Lesson-1-homeowrk/task_3/assignment_01.xlsx

## 4. Baseline Analysis

In [39]:
rating_to_num = {"good": 2, "ok": 1, "bad": 0}

print("=== Pass / Fail Summary ===")
print(evaluated["final_score"].value_counts())
print(f"Pass rate: {(evaluated['final_score'] == 'pass').mean():.0%}")
print()

print("=== Rating Distribution per Criterion ===")
for c in CRITERIA:
    counts = evaluated[c].value_counts()
    print(f"\n{c}:")
    for rating in ["good", "ok", "bad"]:
        print(f"  {rating}: {counts.get(rating, 0)}")

print()
print("=== Average Score per Criterion (good=2, ok=1, bad=0) ===")
avg_scores = {}
for c in CRITERIA:
    numeric = evaluated[c].map(rating_to_num)
    avg_scores[c] = numeric.mean()

sorted_criteria = sorted(avg_scores.items(), key=lambda x: x[1], reverse=True)
for c, score in sorted_criteria:
    print(f"  {c}: {score:.2f}")

print(f"\nBest performing:  {sorted_criteria[0][0]} ({sorted_criteria[0][1]:.2f})")
print(f"Worst performing: {sorted_criteria[-1][0]} ({sorted_criteria[-1][1]:.2f})")

=== Pass / Fail Summary ===
final_score
pass    15
Name: count, dtype: int64
Pass rate: 100%

=== Rating Distribution per Criterion ===

Fluency:
  good: 15
  ok: 0
  bad: 0

Grammar:
  good: 15
  ok: 0
  bad: 0

Tone:
  good: 14
  ok: 1
  bad: 0

Length:
  good: 15
  ok: 0
  bad: 0

Grounding:
  good: 13
  ok: 2
  bad: 0

Latency:
  good: 15
  ok: 0
  bad: 0

Cost:
  good: 15
  ok: 0
  bad: 0

=== Average Score per Criterion (good=2, ok=1, bad=0) ===
  Fluency: 2.00
  Grammar: 2.00
  Length: 2.00
  Latency: 2.00
  Cost: 2.00
  Tone: 1.93
  Grounding: 1.87

Best performing:  Fluency (2.00)
Worst performing: Grounding (1.87)

## Baseline Analysis Summary

- **Best criteria:** Fluency, Grammar, Latency, Cost — all scored a perfect 2.00 across 15 evaluated products. The model consistently produces fluent, grammatically correct text with fast response times and low cost.
- **Worst criterion:** Grounding (1.87) — two descriptions contained slight exaggerations or marketing claims not directly stated in the product data (e.g., "groundbreaking" for MacBook M3, "unparalleled speed" for Razer mouse).
- **Pass rate:** 100% (15/15 passed)
- **Key observations:** The Gemma-2-9b-it model performs well overall on this task. Nearly all descriptions land in the 50–90 word range, the tone is consistently professional, and grammar is clean. The main weakness is occasional grounding issues where the model adds subjective superlatives beyond what the product data states.
- **Improvement strategy for Task 4:** Focus on tightening grounding by adding a few-shot example that demonstrates sticking strictly to provided information. Also try lowering temperature to reduce creative embellishment.